version: '3'
volumes:
  postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
    command: bash -c "bundle exec puma -C config/puma.rb"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
     - database
    ports:
    - 3000:3000
   # volumes:
    #- app-volume:/usr

  database:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
    - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./Docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
    - 80:80

#volumes:
 # app-volume: